apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-simulator
  template:
    metadata:
      labels:
        app: client-simulator
    spec:
      containers:
      - name: client
        image: beta-drone-system:latest
        imagePullPolicy: Never
        command: ["python", "-u", "client_simulator.py"]
        env:
        - name: MQTT_BROKER
          value: "mosquitto-service"
        - name: MQTT_PORT
          value: "1883"