apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone-simulator
spec:
  replicas: 3 # Simuliamo 3 droni attivi di default
  selector:
    matchLabels:
      app: drone-simulator
  template:
    metadata:
      labels:
        app: drone-simulator
    spec:
      containers:
      - name: drone
        image: beta-drone-system:latest
        imagePullPolicy: Never
        command: ["python", "-u", "drone_simulator.py"]
        env:
        - name: MQTT_BROKER
          value: "mosquitto-service"
        - name: MQTT_PORT
          value: "1883"
        - name: DRONE_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name